spring.neo4j1.uri=${SPRING_NEO4J1_URI}
spring.neo4j1.authentication.username=${SPRING_NEO4J1_AUTHENTICATION_USERNAME}
spring.neo4j1.authentication.password=${SPRING_NEO4J1_AUTHENTICATION_PASSWORD}
spring.neo4j2.uri=${SPRING_NEO4J2_URI}
spring.neo4j2.authentication.username=${SPRING_NEO4J2_AUTHENTICATION_USERNAME}
spring.neo4j2.authentication.password=${SPRING_NEO4J2_AUTHENTICATION_PASSWORD}

server.port=${SERVER_PORT}
spring.freemarker.suffix=.ftlh
spring.freemarker.template-loader-path=classpath:/templates/

bezkoder.app.jwtSecret= ${BEZKODER_APP_JWTSECRET}
bezkoder.app.jwtExpirationMs= ${BEZKODER_APP_JWTEXPIRATION}
jwt.public.key=${JWT_PUBLIC_KEY}
hibernate.id.new_generator_mappings=true

spring.jpa.database=postgresql
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.config.import=optional:file:.env[.properties]

#Database Name List

spring.datasource.main.url=${SPRING_DATASOURCE_URL}
spring.datasource.main.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.main.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.main.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
